$image_config = {
	'ID-prehlad-roli' => { :scale => '0.7', :flags => 'htb'},
	'program-system-product' => { :scale => '1.0', :flags => 'htb'},
	'mona-lisa-incremental' => { :scale => '1.0', :flags => 'htb'},
	'mona-lisa-iterative' => { :scale => '1.0', :flags => 'htb'},
	'ID-risk-curves' => { :scale => '0.9', :flags => 'htb'},
	'v-v-fig' => { :scale => '1.0', :flags => 'htb'},
	'skupiny' => { :scale => '0.7', :flags => 'htb'},
	'Procesy' => { :scale => '0.7', :flags => 'htb'},
	'kvalita-cas-naklady' => { :scale => '0.6', :flags => 'htb'},
	'SPLC-fig' => { :scale => '0.45', :flags => 'htb'},
	'entita-preprava-predtym' => { :scale => '0.2', :flags => 'htb'},
	'entita-preprava-potom' => { :scale => '0.6', :flags => 'htb'},
	'requirements-fig' => { :scale => '0.8', :flags => 'htb'},
	'image-architecture-example' => { :scale => '1.0', :flags => 'htb'},
	'maintenance-fig' => { :scale => '0.7', :flags => 'htb'},
	'waterfall-model-fig' => { :scale => '0.65', :flags => 'htb'},
	'v-model-fig' => { :scale => '1.0', :flags => 'htb'},
	'incremental-model-fig' => { :scale => '1.0', :flags => 'htb'},
	'iterative-model-fig' => { :scale => '1.0', :flags => 'htb'},
	'spiral-model-fig' => { :scale => '1.0', :flags => 'htb'},
	'Agile-model-fig' => { :scale => '1.0', :flags => 'htb'},
	'model-comparison-fig' => { :scale => '1.0', :flags => '!htb'},
	'paradigmy' => { :scale => '1.0', :flags => 'htb'},
	'prototypovanie' => { :scale => '1.0', :flags => 'htb'},
	'obrazok-unified-process' => { :scale => '1.0', :flags => 'htb'},
	'obr-UML-diagrams' => { :scale => '1.0', :flags => 'htb'},
	'obr-relationship-types' => { :scale => '0.45', :flags => 'htb'},
	'obr-activity-example' => { :scale => '0.8', :flags => 'p'},
	'obr-use-case-example' => { :scale => '1.0', :flags => 'p'},
	'obr-class-example' => { :scale => '1.0', :flags => 'p'},
	'obr-sequence-example' => { :scale => '0.75', :flags => '!htb'},
	'obr-state-diagram-example' => { :scale => '0.9', :flags => 'htb'},
	'obr-object-diagram-example' => { :scale => '0.75', :flags => 'p'},
	'obr-component-diagram-example' => { :scale => '0.9', :flags => 'p'},
	'obr-package-diagram-example' => { :scale => '0.9', :flags => 'htb'},
	'obr-deployment-diagram-example' => { :scale => '0.7', :flags => 'hbtp'} ,
	
	'agile-modeling' => { :scale => '1.0', :flags => 't'},
}
	#'model-comparison-fig' => { :scale => '1.0', :flags => 'htb', :clearpage_after => 1},
	#'obr-deployment-diagram-example' => { :scale => '0.7', :flags => 'hbtp', :align_top => 1} ,
	
	#'agile-modeling' => { :scale => '1.0', :flags => 't',  :align_top => 1},
