pdflatex master.tex
bibtex master.aux
bibtex master-blx.aux
bibtex master1-blx.aux
bibtex master2-blx.aux
bibtex master3-blx.aux
bibtex master4-blx.aux
bibtex master5-blx.aux
bibtex master6-blx.aux
bibtex master7-blx.aux
bibtex master8-blx.aux
bibtex master9-blx.aux
bibtex master10-blx.aux
bibtex master11-blx.aux
bibtex master12-blx.aux
bibtex master13-blx.aux
bibtex master14-blx.aux
bibtex master15-blx.aux
bibtex master16-blx.aux
pdflatex master.tex
xindy -M texindy -M page-ranges -C utf8 -L czech master.idx
pdflatex master.tex
